name: Patch Service Version in Platform

on:
  #push:
  #  tags:
  #    - "v*"
  workflow_dispatch:
    inputs:
      tag:
        description: 'The tag to apply to the service.'
        required: true

jobs:
  release-notification:
    uses: spread-ai/github-workflows/.github/workflows/patch-platform.yaml@main
    secrets: inherit
