name: Release Drafter

on:
  push:
    branches:
      - main
      - master
  pull_request_target:
    types: [ opened, reopened, synchronize ]
  workflow_call:
    inputs:
      main-branch:
        required: true
        type: string
        default: 'main'

permissions:
  contents: read

jobs:
  update_release_draft:
    name: Update Release Draft
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        with:
          commitish: ${{ inputs.main-branch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
