name: Scan License

on:
  push:
    branches:
      - '**'

permissions:
  contents: read

jobs:
  scan-license:
    name: Scan License
    uses: spread-ai/github-workflows/.github/workflows/scan-node-license.yaml@main
    secrets: inherit
    with:
      node-version: "v16.14.2"
